name: Helidon CI
on:
  push:
    branches: [ "main" ]
    paths:
      - 'helidon-mp-app/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'helidon-mp-app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./helidon-mp-app

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and run tests
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: postgres
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
        run: |
          mvn clean compile
          mvn test

      - name: Package application
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: postgres
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
        run: mvn package -DskipTests

      - name: Run native tests
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: postgres
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
        run: |
          mvn -Pnative-image install -DskipTests